### ISSUE TITLE
Change the text color of that part

### ISSUE THREAD

**Issue by rohansood42** [athkalia/EmphasisTextView#2]
Change the text color of that part rather than changing the background color would be a great enhancement

**Comment by athkalia** [comment]
Yes, not a bad idea. I was planning to make a release in May, so I'll have a look at that as well. Or maybe you want to contribute this yourself?

**Comment by rohansood42** [comment]
@athkalia Surely once my exams get over i will try working on it.

**Comment by athkalia** [comment]
Hey, this functionality has been added in the new v0.4 version! enjoy
